version: '2.2'

services:
  search:
    build: apps/algorithm/search
    container_name: martletplace_search
    restart: unless-stopped
    depends_on: []
    volumes: [ ./apps/algorithm/search/src:/app/src ]
    environment: []
    ports: [ 8221:8221 ]

  database:
    build: apps/data/database
    container_name: martletplace_database
    restart: unless-stopped
    depends_on: []
    volumes: []
    environment:
      - POSTGRES_PASSWORD=johuigytfrdcv
    ports: [ 8310:8310 ]
