version: '2.2'

services:
  listing:
    build: apps/backend/listing
    container_name: martletplace_listing
    restart: unless-stopped
    depends_on: []
    volumes: [ ./apps/backend/listing/src:/app/src ]
    environment: []
    ports: [ 8212:8212 ]
