version: '2.2'

services:
  recommend:
    build: apps/algorithm/recommend
    container_name: martletplace_recommend
    restart: unless-stopped
    depends_on: []
    volumes: [ ./apps/algorithm/recommend/src:/app/src ]
    environment: []
    ports: [ 8222:8222 ]
