name: Datalayer

on:
  push:
    branches: ["master"]
  pull_request:

defaults:
  run:
    working-directory: apps/data/datalayer

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@1.78.0
        with:
          components: clippy

      - name: Lint
        run: RUSTFLAGS="-Dwarnings" cargo clippy --all-targets --all-features

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@1.78.0
        with:
          components: rustfmt

      - name: Format
        run: cargo fmt --all -- --check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@1.78.0

      - name: Test
        run: cargo test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@1.78.0

      - name: Build
        run: cargo build

  security:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@1.78.0

      - name: Install cargo-audit
        run: cargo install cargo-audit --locked

      - name: Scan
        run: cargo audit
