name: PR

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  check_pull_requests:
    name: Linked Issue
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - uses: nearform-actions/github-action-check-linked-issues@v1
        with:
          comment: false
