name: Review

on:
  push:
    branches: ["master"]
  pull_request:

env:
  NODE_VERSION: "20.x"

defaults:
  run:
    working-directory: apps/backend/review

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Format
        run: npm run format:ci

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test:ci

  security:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Nodejs Scan
        uses: ajinabraham/njsscan-action@master
        with:
          args: './apps/backend/review'
