name: Search

on:
  push:
    branches: ["master"]
  pull_request:

env:
  PYTHON_VERSION: "3.12"

defaults:
  run:
    working-directory: apps/algorithm/search

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: chartboost/ruff-action@v1
        with:
          src: "./apps/algorithm/search"
          args: 'check'

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: chartboost/ruff-action@v1
        with:
          src: "./apps/algorithm/search"
          args: 'format --check'

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Compose Up
        run: docker compose up -d search datalayer elasticsearch

      - name: Test
        run: docker compose exec search pytest

  security:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test
        run: bandit -c .bandit -ll -ii -n 3 -a file -r src/
