name: Security

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Secret Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --only-verified